name: quoridouble
description: "Quoridor game app"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  provider: ^6.0.0
  flutter_svg: ^2.0.14
  pathfinding: ^3.0.1
  socket_io_client: ^3.0.2
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^6.1.0
  lottie: ^3.1.3
  fluttertoast: ^8.2.8
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Verdana
      fonts:
        - asset: assets/fonts/Verdana.ttf

  assets:
    - assets/images/
    - assets/lotties/
    - assets/translations/
    - .env
