name: Commit Message Check

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check Commit Message Format
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^((feat|add|fix|!hotfix|refactor|docs|rename|remove|ci|build|chore|test)?(?:\(([^\A-Z)\s]+)?\))?(\!)?: (.+))(\n{2}|$)(((?:^.+(\n|$))+(?:\n|$){0,2}?)+(?:(^.+(\n|$))+)|(?:^.+$))?'
          error: "The commit message must follow the format of the git karma (http://karma-runner.github.io/4.0/dev/git-commit-msg.html)."
        env:
          CI: true
