name: Flutter Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions: write-all
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      # 저장소 클론
      - name: Checkout code
        uses: actions/checkout@v3

      # Java 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Flutter SDK 설치
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      # .env 파일 설정
      - name: Set .env as environment variables
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}

        run: |
          cd app
          echo "SERVER_URL=${SERVER_URL}" >> .env
          echo "SERVER_CODE=${SERVER_CODE}" >> .env

      # 의존성 설치
      - name: Install Dependencies
        run: |
          cd app
          flutter pub get

      # 빌드 실행
      - name: Build APK
        run: |
          cd app
          flutter build apk --release

      # 빌드 결과 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk

      # GitHub 릴리즈에 업로드
      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/app/outputs/flutter-apk/app-release.apk"
